# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pad',
            name='status',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
