# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pads', '0002_pad_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pad',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pad',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
