# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pads', '0003_auto_20170327_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('status', models.CharField(blank=True, default='available', max_length=20, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('pad', models.ManyToManyField(to='pads.Pad')),
            ],
        ),
    ]
